// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Solve")>]
[<assembly: AssemblyProductAttribute("Solve")>]
[<assembly: AssemblyDescriptionAttribute("Prolog F# implementation")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Solve"
    let [<Literal>] AssemblyProduct = "Solve"
    let [<Literal>] AssemblyDescription = "Prolog F# implementation"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
