// Implementation file for parser generated by fsyacc
module PrologParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "PrologParser.fsy"

open Solve

open Solve.TermTypes
open Solve.TermTypes.Transformers

open Solve.Rule
open Solve.Rule.Transformers

type ParseResult =
    | RuleParseResult of Rule
    | CallParseResult of Goal

# 20 "PrologParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | QUESTION_MARK
  | DOT
  | COMMA
  | SLASH
  | ASTERISK
  | MINUS
  | PLUS
  | COLON
  | RIGHT_BRACK
  | LEFT_BRACK
  | RIGHT_BRACKET
  | LEFT_BRACKET
  | NULL
  | FALSE
  | TRUE
  | IS
  | STRING of (string)
  | VAR of (string)
  | ATOM of (string)
  | INT of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_QUESTION_MARK
    | TOKEN_DOT
    | TOKEN_COMMA
    | TOKEN_SLASH
    | TOKEN_ASTERISK
    | TOKEN_MINUS
    | TOKEN_PLUS
    | TOKEN_COLON
    | TOKEN_RIGHT_BRACK
    | TOKEN_LEFT_BRACK
    | TOKEN_RIGHT_BRACKET
    | TOKEN_LEFT_BRACKET
    | TOKEN_NULL
    | TOKEN_FALSE
    | TOKEN_TRUE
    | TOKEN_IS
    | TOKEN_STRING
    | TOKEN_VAR
    | TOKEN_ATOM
    | TOKEN_INT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_prog
    | NONTERM_fact
    | NONTERM_rule
    | NONTERM_signature
    | NONTERM_goal
    | NONTERM_parameter
    | NONTERM_parameterList
    | NONTERM_termList
    | NONTERM_body
    | NONTERM_calcExpr
    | NONTERM_term

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | QUESTION_MARK  -> 1 
  | DOT  -> 2 
  | COMMA  -> 3 
  | SLASH  -> 4 
  | ASTERISK  -> 5 
  | MINUS  -> 6 
  | PLUS  -> 7 
  | COLON  -> 8 
  | RIGHT_BRACK  -> 9 
  | LEFT_BRACK  -> 10 
  | RIGHT_BRACKET  -> 11 
  | LEFT_BRACKET  -> 12 
  | NULL  -> 13 
  | FALSE  -> 14 
  | TRUE  -> 15 
  | IS  -> 16 
  | STRING _ -> 17 
  | VAR _ -> 18 
  | ATOM _ -> 19 
  | INT _ -> 20 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_QUESTION_MARK 
  | 2 -> TOKEN_DOT 
  | 3 -> TOKEN_COMMA 
  | 4 -> TOKEN_SLASH 
  | 5 -> TOKEN_ASTERISK 
  | 6 -> TOKEN_MINUS 
  | 7 -> TOKEN_PLUS 
  | 8 -> TOKEN_COLON 
  | 9 -> TOKEN_RIGHT_BRACK 
  | 10 -> TOKEN_LEFT_BRACK 
  | 11 -> TOKEN_RIGHT_BRACKET 
  | 12 -> TOKEN_LEFT_BRACKET 
  | 13 -> TOKEN_NULL 
  | 14 -> TOKEN_FALSE 
  | 15 -> TOKEN_TRUE 
  | 16 -> TOKEN_IS 
  | 17 -> TOKEN_STRING 
  | 18 -> TOKEN_VAR 
  | 19 -> TOKEN_ATOM 
  | 20 -> TOKEN_INT 
  | 23 -> TOKEN_end_of_input
  | 21 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_prog 
    | 3 -> NONTERM_prog 
    | 4 -> NONTERM_prog 
    | 5 -> NONTERM_prog 
    | 6 -> NONTERM_fact 
    | 7 -> NONTERM_rule 
    | 8 -> NONTERM_signature 
    | 9 -> NONTERM_goal 
    | 10 -> NONTERM_parameter 
    | 11 -> NONTERM_parameterList 
    | 12 -> NONTERM_parameterList 
    | 13 -> NONTERM_parameterList 
    | 14 -> NONTERM_termList 
    | 15 -> NONTERM_termList 
    | 16 -> NONTERM_termList 
    | 17 -> NONTERM_body 
    | 18 -> NONTERM_body 
    | 19 -> NONTERM_body 
    | 20 -> NONTERM_body 
    | 21 -> NONTERM_body 
    | 22 -> NONTERM_body 
    | 23 -> NONTERM_calcExpr 
    | 24 -> NONTERM_calcExpr 
    | 25 -> NONTERM_calcExpr 
    | 26 -> NONTERM_calcExpr 
    | 27 -> NONTERM_calcExpr 
    | 28 -> NONTERM_term 
    | 29 -> NONTERM_term 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 23 
let _fsyacc_tagOfErrorTerminal = 21

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | QUESTION_MARK  -> "QUESTION_MARK" 
  | DOT  -> "DOT" 
  | COMMA  -> "COMMA" 
  | SLASH  -> "SLASH" 
  | ASTERISK  -> "ASTERISK" 
  | MINUS  -> "MINUS" 
  | PLUS  -> "PLUS" 
  | COLON  -> "COLON" 
  | RIGHT_BRACK  -> "RIGHT_BRACK" 
  | LEFT_BRACK  -> "LEFT_BRACK" 
  | RIGHT_BRACKET  -> "RIGHT_BRACKET" 
  | LEFT_BRACKET  -> "LEFT_BRACKET" 
  | NULL  -> "NULL" 
  | FALSE  -> "FALSE" 
  | TRUE  -> "TRUE" 
  | IS  -> "IS" 
  | STRING _ -> "STRING" 
  | VAR _ -> "VAR" 
  | ATOM _ -> "ATOM" 
  | INT _ -> "INT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | QUESTION_MARK  -> (null : System.Object) 
  | DOT  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | SLASH  -> (null : System.Object) 
  | ASTERISK  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | RIGHT_BRACK  -> (null : System.Object) 
  | LEFT_BRACK  -> (null : System.Object) 
  | RIGHT_BRACKET  -> (null : System.Object) 
  | LEFT_BRACKET  -> (null : System.Object) 
  | NULL  -> (null : System.Object) 
  | FALSE  -> (null : System.Object) 
  | TRUE  -> (null : System.Object) 
  | IS  -> (null : System.Object) 
  | STRING _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | VAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ATOM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 1us; 65535us; 0us; 7us; 1us; 65535us; 0us; 8us; 1us; 65535us; 0us; 9us; 4us; 65535us; 5us; 6us; 11us; 31us; 37us; 31us; 38us; 31us; 2us; 65535us; 15us; 23us; 24us; 25us; 1us; 65535us; 15us; 16us; 1us; 65535us; 19us; 20us; 3us; 65535us; 11us; 12us; 37us; 35us; 38us; 36us; 5us; 65535us; 33us; 34us; 44us; 40us; 45us; 41us; 46us; 42us; 47us; 43us; 12us; 65535us; 11us; 32us; 15us; 22us; 19us; 26us; 24us; 22us; 27us; 28us; 33us; 39us; 37us; 32us; 38us; 32us; 44us; 39us; 45us; 39us; 46us; 39us; 47us; 39us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 7us; 9us; 11us; 16us; 19us; 21us; 23us; 27us; 33us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 5us; 2us; 6us; 7us; 1us; 7us; 1us; 7us; 3us; 7us; 21us; 22us; 1us; 7us; 1us; 8us; 1us; 8us; 2us; 8us; 12us; 1us; 8us; 1us; 9us; 1us; 9us; 2us; 9us; 15us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 17us; 1us; 18us; 1us; 19us; 1us; 20us; 1us; 20us; 5us; 20us; 24us; 25us; 26us; 27us; 3us; 21us; 21us; 22us; 3us; 21us; 22us; 22us; 1us; 21us; 1us; 22us; 1us; 23us; 5us; 24us; 24us; 25us; 26us; 27us; 5us; 24us; 25us; 25us; 26us; 27us; 5us; 24us; 25us; 26us; 26us; 27us; 5us; 24us; 25us; 26us; 27us; 27us; 1us; 24us; 1us; 25us; 1us; 26us; 1us; 27us; 1us; 28us; 1us; 29us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 21us; 23us; 25us; 29us; 31us; 33us; 35us; 38us; 40us; 42us; 44us; 47us; 49us; 51us; 53us; 55us; 57us; 59us; 61us; 63us; 65us; 67us; 69us; 71us; 73us; 79us; 83us; 87us; 89us; 91us; 93us; 99us; 105us; 111us; 117us; 119us; 121us; 123us; 125us; 127us; |]
let _fsyacc_action_rows = 50
let _fsyacc_actionTableElements = [|3us; 32768us; 0us; 3us; 1us; 4us; 19us; 14us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 1us; 32768us; 6us; 5us; 1us; 32768us; 19us; 18us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 1us; 16390us; 8us; 10us; 1us; 32768us; 6us; 11us; 5us; 32768us; 14us; 30us; 15us; 29us; 18us; 49us; 19us; 18us; 20us; 48us; 3us; 32768us; 2us; 13us; 3us; 37us; 8us; 38us; 0us; 16391us; 1us; 32768us; 12us; 15us; 2us; 16397us; 18us; 49us; 20us; 48us; 2us; 32768us; 3us; 24us; 11us; 17us; 0us; 16392us; 1us; 32768us; 12us; 19us; 2us; 16400us; 18us; 49us; 20us; 48us; 2us; 32768us; 3us; 27us; 11us; 21us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 2us; 32768us; 18us; 49us; 20us; 48us; 0us; 16396us; 0us; 16398us; 2us; 32768us; 18us; 49us; 20us; 48us; 0us; 16399us; 0us; 16401us; 0us; 16402us; 0us; 16403us; 1us; 32768us; 16us; 33us; 2us; 32768us; 18us; 49us; 20us; 48us; 4us; 16404us; 4us; 47us; 5us; 46us; 6us; 45us; 7us; 44us; 2us; 16405us; 3us; 37us; 8us; 38us; 2us; 16406us; 3us; 37us; 8us; 38us; 5us; 32768us; 14us; 30us; 15us; 29us; 18us; 49us; 19us; 18us; 20us; 48us; 5us; 32768us; 14us; 30us; 15us; 29us; 18us; 49us; 19us; 18us; 20us; 48us; 0us; 16407us; 4us; 16408us; 4us; 47us; 5us; 46us; 6us; 45us; 7us; 44us; 4us; 16409us; 4us; 47us; 5us; 46us; 6us; 45us; 7us; 44us; 4us; 16410us; 4us; 47us; 5us; 46us; 6us; 45us; 7us; 44us; 4us; 16411us; 4us; 47us; 5us; 46us; 6us; 45us; 7us; 44us; 2us; 32768us; 18us; 49us; 20us; 48us; 2us; 32768us; 18us; 49us; 20us; 48us; 2us; 32768us; 18us; 49us; 20us; 48us; 2us; 32768us; 18us; 49us; 20us; 48us; 0us; 16412us; 0us; 16413us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 6us; 7us; 9us; 11us; 12us; 13us; 14us; 16us; 18us; 24us; 28us; 29us; 31us; 34us; 37us; 38us; 40us; 43us; 46us; 47us; 48us; 49us; 52us; 53us; 54us; 57us; 58us; 59us; 60us; 61us; 63us; 66us; 71us; 74us; 77us; 83us; 89us; 90us; 95us; 100us; 105us; 110us; 113us; 116us; 119us; 122us; 123us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 3us; 1us; 1us; 1us; 5us; 4us; 4us; 1us; 1us; 3us; 0us; 1us; 3us; 0us; 1us; 1us; 1us; 3us; 3us; 3us; 1us; 3us; 3us; 3us; 3us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 3us; 4us; 5us; 6us; 7us; 8us; 8us; 8us; 9us; 9us; 9us; 10us; 10us; 10us; 10us; 10us; 10us; 11us; 11us; 11us; 11us; 11us; 12us; 12us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 65535us; 65535us; 16387us; 16388us; 16389us; 65535us; 65535us; 65535us; 65535us; 16391us; 65535us; 65535us; 65535us; 16392us; 65535us; 65535us; 65535us; 16393us; 16394us; 16395us; 65535us; 16396us; 16398us; 65535us; 16399us; 16401us; 16402us; 16403us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16407us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16412us; 16413us; |]
let _fsyacc_reductions ()  =    [| 
# 236 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : ParseResult option)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 245 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "PrologParser.fsy"
                                   _1 
                   )
# 43 "PrologParser.fsy"
                 : ParseResult option));
# 256 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "PrologParser.fsy"
                              None 
                   )
# 46 "PrologParser.fsy"
                 : 'prog));
# 266 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'goal)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "PrologParser.fsy"
                                                   Some <| CallParseResult _3 
                   )
# 47 "PrologParser.fsy"
                 : 'prog));
# 277 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'fact)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "PrologParser.fsy"
                               Some <| RuleParseResult _1 
                   )
# 48 "PrologParser.fsy"
                 : 'prog));
# 288 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rule)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "PrologParser.fsy"
                               Some <| RuleParseResult _1 
                   )
# 49 "PrologParser.fsy"
                 : 'prog));
# 299 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'signature)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "PrologParser.fsy"
                                    Rule(_1, True) 
                   )
# 52 "PrologParser.fsy"
                 : 'fact));
# 310 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'signature)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "PrologParser.fsy"
                                                            Rule(_1, _4) 
                   )
# 55 "PrologParser.fsy"
                 : 'rule));
# 322 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameterList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "PrologParser.fsy"
                                                                        Signature(_1, _3) 
                   )
# 58 "PrologParser.fsy"
                 : 'signature));
# 334 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'termList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "PrologParser.fsy"
                                                                   Solve.Rule.Goal(Solve.TermTypes.Structure(_1, _3)) 
                   )
# 61 "PrologParser.fsy"
                 : 'goal));
# 346 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "PrologParser.fsy"
                                  Parameter(_1) 
                   )
# 64 "PrologParser.fsy"
                 : 'parameter));
# 357 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameter)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "PrologParser.fsy"
                                    [_1] 
                   )
# 67 "PrologParser.fsy"
                 : 'parameterList));
# 368 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameterList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameter)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "PrologParser.fsy"
                                                           _3::_1 
                   )
# 68 "PrologParser.fsy"
                 : 'parameterList));
# 380 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "PrologParser.fsy"
                          [] 
                   )
# 69 "PrologParser.fsy"
                 : 'parameterList));
# 390 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 72 "PrologParser.fsy"
                               [_1] 
                   )
# 72 "PrologParser.fsy"
                 : 'termList));
# 401 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'termList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 73 "PrologParser.fsy"
                                                 _3::_1 
                   )
# 73 "PrologParser.fsy"
                 : 'termList));
# 413 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 74 "PrologParser.fsy"
                          [] 
                   )
# 74 "PrologParser.fsy"
                 : 'termList));
# 423 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 77 "PrologParser.fsy"
                                  True 
                   )
# 77 "PrologParser.fsy"
                 : 'body));
# 433 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 78 "PrologParser.fsy"
                                False 
                   )
# 78 "PrologParser.fsy"
                 : 'body));
# 443 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'goal)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 79 "PrologParser.fsy"
                               CallExpression(_1) 
                   )
# 79 "PrologParser.fsy"
                 : 'body));
# 454 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 80 "PrologParser.fsy"
                                           CalcExpr(_1, _3) 
                   )
# 80 "PrologParser.fsy"
                 : 'body));
# 466 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 81 "PrologParser.fsy"
                                          AndExpression(_1, _3) 
                   )
# 81 "PrologParser.fsy"
                 : 'body));
# 478 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 82 "PrologParser.fsy"
                                          OrExpression(_1, _3) 
                   )
# 82 "PrologParser.fsy"
                 : 'body));
# 490 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "PrologParser.fsy"
                               Value(CalcAny(_1)) 
                   )
# 85 "PrologParser.fsy"
                 : 'calcExpr));
# 501 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 86 "PrologParser.fsy"
                                                 Plus(CalcInner(_1), CalcInner(_3)) 
                   )
# 86 "PrologParser.fsy"
                 : 'calcExpr));
# 513 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 87 "PrologParser.fsy"
                                                  Subsctruct(CalcInner(_1), CalcInner(_3)) 
                   )
# 87 "PrologParser.fsy"
                 : 'calcExpr));
# 525 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 88 "PrologParser.fsy"
                                                     Multiply(CalcInner(_1), CalcInner(_3)) 
                   )
# 88 "PrologParser.fsy"
                 : 'calcExpr));
# 537 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 89 "PrologParser.fsy"
                                                  Division(CalcInner(_1), CalcInner(_3)) 
                   )
# 89 "PrologParser.fsy"
                 : 'calcExpr));
# 549 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 92 "PrologParser.fsy"
                              TypedTerm(TypedNumberTerm(NumberTerm (float _1))) 
                   )
# 92 "PrologParser.fsy"
                 : 'term));
# 560 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 93 "PrologParser.fsy"
                              VariableTerm(Variable(_1)) 
                   )
# 93 "PrologParser.fsy"
                 : 'term));
|]
# 572 "PrologParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 24;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : ParseResult option =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
