// Implementation file for parser generated by fsyacc
module PrologParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "PrologParser.fsy"

open Solve

open Solve.TermTypes
open Solve.TermTypes.Transformers

open Solve.Rule
open Solve.Rule.Transformers

type ParseResult =
    | RuleParseResult of Rule
    | CallParseResult of Goal

# 20 "PrologParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | LESS_THAN_SIGN
  | GREATER_THAN_SIGN
  | EQUALS_SIGN
  | QUESTION_MARK
  | DOT
  | COMMA
  | SLASH
  | ASTERISK
  | MINUS
  | PLUS
  | COLON
  | RIGHT_BRACK
  | LEFT_BRACK
  | RIGHT_BRACKET
  | LEFT_BRACKET
  | NULL
  | FALSE
  | TRUE
  | IS
  | STRING of (string)
  | VAR of (string)
  | ATOM of (string)
  | INT of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_LESS_THAN_SIGN
    | TOKEN_GREATER_THAN_SIGN
    | TOKEN_EQUALS_SIGN
    | TOKEN_QUESTION_MARK
    | TOKEN_DOT
    | TOKEN_COMMA
    | TOKEN_SLASH
    | TOKEN_ASTERISK
    | TOKEN_MINUS
    | TOKEN_PLUS
    | TOKEN_COLON
    | TOKEN_RIGHT_BRACK
    | TOKEN_LEFT_BRACK
    | TOKEN_RIGHT_BRACKET
    | TOKEN_LEFT_BRACKET
    | TOKEN_NULL
    | TOKEN_FALSE
    | TOKEN_TRUE
    | TOKEN_IS
    | TOKEN_STRING
    | TOKEN_VAR
    | TOKEN_ATOM
    | TOKEN_INT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_prog
    | NONTERM_fact
    | NONTERM_rule
    | NONTERM_signature
    | NONTERM_goal
    | NONTERM_parameter
    | NONTERM_parameterList
    | NONTERM_termList
    | NONTERM_body
    | NONTERM_calcExpr
    | NONTERM_term

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | LESS_THAN_SIGN  -> 1 
  | GREATER_THAN_SIGN  -> 2 
  | EQUALS_SIGN  -> 3 
  | QUESTION_MARK  -> 4 
  | DOT  -> 5 
  | COMMA  -> 6 
  | SLASH  -> 7 
  | ASTERISK  -> 8 
  | MINUS  -> 9 
  | PLUS  -> 10 
  | COLON  -> 11 
  | RIGHT_BRACK  -> 12 
  | LEFT_BRACK  -> 13 
  | RIGHT_BRACKET  -> 14 
  | LEFT_BRACKET  -> 15 
  | NULL  -> 16 
  | FALSE  -> 17 
  | TRUE  -> 18 
  | IS  -> 19 
  | STRING _ -> 20 
  | VAR _ -> 21 
  | ATOM _ -> 22 
  | INT _ -> 23 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_LESS_THAN_SIGN 
  | 2 -> TOKEN_GREATER_THAN_SIGN 
  | 3 -> TOKEN_EQUALS_SIGN 
  | 4 -> TOKEN_QUESTION_MARK 
  | 5 -> TOKEN_DOT 
  | 6 -> TOKEN_COMMA 
  | 7 -> TOKEN_SLASH 
  | 8 -> TOKEN_ASTERISK 
  | 9 -> TOKEN_MINUS 
  | 10 -> TOKEN_PLUS 
  | 11 -> TOKEN_COLON 
  | 12 -> TOKEN_RIGHT_BRACK 
  | 13 -> TOKEN_LEFT_BRACK 
  | 14 -> TOKEN_RIGHT_BRACKET 
  | 15 -> TOKEN_LEFT_BRACKET 
  | 16 -> TOKEN_NULL 
  | 17 -> TOKEN_FALSE 
  | 18 -> TOKEN_TRUE 
  | 19 -> TOKEN_IS 
  | 20 -> TOKEN_STRING 
  | 21 -> TOKEN_VAR 
  | 22 -> TOKEN_ATOM 
  | 23 -> TOKEN_INT 
  | 26 -> TOKEN_end_of_input
  | 24 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_prog 
    | 3 -> NONTERM_prog 
    | 4 -> NONTERM_prog 
    | 5 -> NONTERM_prog 
    | 6 -> NONTERM_fact 
    | 7 -> NONTERM_rule 
    | 8 -> NONTERM_signature 
    | 9 -> NONTERM_goal 
    | 10 -> NONTERM_parameter 
    | 11 -> NONTERM_parameterList 
    | 12 -> NONTERM_parameterList 
    | 13 -> NONTERM_parameterList 
    | 14 -> NONTERM_termList 
    | 15 -> NONTERM_termList 
    | 16 -> NONTERM_termList 
    | 17 -> NONTERM_body 
    | 18 -> NONTERM_body 
    | 19 -> NONTERM_body 
    | 20 -> NONTERM_body 
    | 21 -> NONTERM_body 
    | 22 -> NONTERM_body 
    | 23 -> NONTERM_body 
    | 24 -> NONTERM_body 
    | 25 -> NONTERM_body 
    | 26 -> NONTERM_calcExpr 
    | 27 -> NONTERM_calcExpr 
    | 28 -> NONTERM_calcExpr 
    | 29 -> NONTERM_calcExpr 
    | 30 -> NONTERM_calcExpr 
    | 31 -> NONTERM_term 
    | 32 -> NONTERM_term 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 26 
let _fsyacc_tagOfErrorTerminal = 24

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | LESS_THAN_SIGN  -> "LESS_THAN_SIGN" 
  | GREATER_THAN_SIGN  -> "GREATER_THAN_SIGN" 
  | EQUALS_SIGN  -> "EQUALS_SIGN" 
  | QUESTION_MARK  -> "QUESTION_MARK" 
  | DOT  -> "DOT" 
  | COMMA  -> "COMMA" 
  | SLASH  -> "SLASH" 
  | ASTERISK  -> "ASTERISK" 
  | MINUS  -> "MINUS" 
  | PLUS  -> "PLUS" 
  | COLON  -> "COLON" 
  | RIGHT_BRACK  -> "RIGHT_BRACK" 
  | LEFT_BRACK  -> "LEFT_BRACK" 
  | RIGHT_BRACKET  -> "RIGHT_BRACKET" 
  | LEFT_BRACKET  -> "LEFT_BRACKET" 
  | NULL  -> "NULL" 
  | FALSE  -> "FALSE" 
  | TRUE  -> "TRUE" 
  | IS  -> "IS" 
  | STRING _ -> "STRING" 
  | VAR _ -> "VAR" 
  | ATOM _ -> "ATOM" 
  | INT _ -> "INT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | LESS_THAN_SIGN  -> (null : System.Object) 
  | GREATER_THAN_SIGN  -> (null : System.Object) 
  | EQUALS_SIGN  -> (null : System.Object) 
  | QUESTION_MARK  -> (null : System.Object) 
  | DOT  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | SLASH  -> (null : System.Object) 
  | ASTERISK  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | RIGHT_BRACK  -> (null : System.Object) 
  | LEFT_BRACK  -> (null : System.Object) 
  | RIGHT_BRACKET  -> (null : System.Object) 
  | LEFT_BRACKET  -> (null : System.Object) 
  | NULL  -> (null : System.Object) 
  | FALSE  -> (null : System.Object) 
  | TRUE  -> (null : System.Object) 
  | IS  -> (null : System.Object) 
  | STRING _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | VAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ATOM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 1us; 65535us; 0us; 8us; 1us; 65535us; 0us; 9us; 1us; 65535us; 0us; 10us; 4us; 65535us; 5us; 6us; 12us; 32us; 38us; 32us; 39us; 32us; 2us; 65535us; 16us; 24us; 25us; 26us; 1us; 65535us; 16us; 17us; 1us; 65535us; 20us; 21us; 3us; 65535us; 12us; 13us; 38us; 36us; 39us; 37us; 5us; 65535us; 34us; 35us; 51us; 47us; 52us; 48us; 53us; 49us; 54us; 50us; 15us; 65535us; 12us; 33us; 16us; 23us; 20us; 27us; 25us; 23us; 28us; 29us; 34us; 46us; 38us; 33us; 39us; 33us; 40us; 41us; 42us; 43us; 44us; 45us; 51us; 46us; 52us; 46us; 53us; 46us; 54us; 46us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 7us; 9us; 11us; 16us; 19us; 21us; 23us; 27us; 33us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 5us; 2us; 6us; 7us; 1us; 7us; 1us; 7us; 3us; 7us; 21us; 22us; 1us; 7us; 1us; 8us; 1us; 8us; 2us; 8us; 12us; 1us; 8us; 1us; 9us; 1us; 9us; 2us; 9us; 15us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 17us; 1us; 18us; 1us; 19us; 4us; 20us; 23us; 24us; 25us; 1us; 20us; 5us; 20us; 27us; 28us; 29us; 30us; 3us; 21us; 21us; 22us; 3us; 21us; 22us; 22us; 1us; 21us; 1us; 22us; 1us; 23us; 1us; 23us; 1us; 24us; 1us; 24us; 1us; 25us; 1us; 25us; 1us; 26us; 5us; 27us; 27us; 28us; 29us; 30us; 5us; 27us; 28us; 28us; 29us; 30us; 5us; 27us; 28us; 29us; 29us; 30us; 5us; 27us; 28us; 29us; 30us; 30us; 1us; 27us; 1us; 28us; 1us; 29us; 1us; 30us; 1us; 31us; 1us; 32us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 20us; 23us; 25us; 27us; 31us; 33us; 35us; 37us; 40us; 42us; 44us; 46us; 49us; 51us; 53us; 55us; 57us; 59us; 61us; 63us; 65us; 67us; 69us; 71us; 76us; 78us; 84us; 88us; 92us; 94us; 96us; 98us; 100us; 102us; 104us; 106us; 108us; 110us; 116us; 122us; 128us; 134us; 136us; 138us; 140us; 142us; 144us; |]
let _fsyacc_action_rows = 57
let _fsyacc_actionTableElements = [|3us; 32768us; 0us; 3us; 4us; 4us; 22us; 15us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 1us; 32768us; 9us; 5us; 1us; 32768us; 22us; 19us; 1us; 32768us; 5us; 7us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 1us; 16390us; 11us; 11us; 1us; 32768us; 9us; 12us; 5us; 32768us; 17us; 31us; 18us; 30us; 21us; 56us; 22us; 19us; 23us; 55us; 3us; 32768us; 5us; 14us; 6us; 38us; 11us; 39us; 0us; 16391us; 1us; 32768us; 15us; 16us; 2us; 16397us; 21us; 56us; 23us; 55us; 2us; 32768us; 6us; 25us; 14us; 18us; 0us; 16392us; 1us; 32768us; 15us; 20us; 2us; 16400us; 21us; 56us; 23us; 55us; 2us; 32768us; 6us; 28us; 14us; 22us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 2us; 32768us; 21us; 56us; 23us; 55us; 0us; 16396us; 0us; 16398us; 2us; 32768us; 21us; 56us; 23us; 55us; 0us; 16399us; 0us; 16401us; 0us; 16402us; 0us; 16403us; 4us; 32768us; 1us; 44us; 2us; 42us; 3us; 40us; 19us; 34us; 2us; 32768us; 21us; 56us; 23us; 55us; 4us; 16404us; 7us; 54us; 8us; 53us; 9us; 52us; 10us; 51us; 2us; 16405us; 6us; 38us; 11us; 39us; 2us; 16406us; 6us; 38us; 11us; 39us; 5us; 32768us; 17us; 31us; 18us; 30us; 21us; 56us; 22us; 19us; 23us; 55us; 5us; 32768us; 17us; 31us; 18us; 30us; 21us; 56us; 22us; 19us; 23us; 55us; 2us; 32768us; 21us; 56us; 23us; 55us; 0us; 16407us; 2us; 32768us; 21us; 56us; 23us; 55us; 0us; 16408us; 2us; 32768us; 21us; 56us; 23us; 55us; 0us; 16409us; 0us; 16410us; 4us; 16411us; 7us; 54us; 8us; 53us; 9us; 52us; 10us; 51us; 4us; 16412us; 7us; 54us; 8us; 53us; 9us; 52us; 10us; 51us; 4us; 16413us; 7us; 54us; 8us; 53us; 9us; 52us; 10us; 51us; 4us; 16414us; 7us; 54us; 8us; 53us; 9us; 52us; 10us; 51us; 2us; 32768us; 21us; 56us; 23us; 55us; 2us; 32768us; 21us; 56us; 23us; 55us; 2us; 32768us; 21us; 56us; 23us; 55us; 2us; 32768us; 21us; 56us; 23us; 55us; 0us; 16415us; 0us; 16416us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 6us; 7us; 9us; 11us; 13us; 14us; 15us; 16us; 18us; 20us; 26us; 30us; 31us; 33us; 36us; 39us; 40us; 42us; 45us; 48us; 49us; 50us; 51us; 54us; 55us; 56us; 59us; 60us; 61us; 62us; 63us; 68us; 71us; 76us; 79us; 82us; 88us; 94us; 97us; 98us; 101us; 102us; 105us; 106us; 107us; 112us; 117us; 122us; 127us; 130us; 133us; 136us; 139us; 140us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 4us; 1us; 1us; 1us; 5us; 4us; 4us; 1us; 1us; 3us; 0us; 1us; 3us; 0us; 1us; 1us; 1us; 3us; 3us; 3us; 3us; 3us; 3us; 1us; 3us; 3us; 3us; 3us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 3us; 4us; 5us; 6us; 7us; 8us; 8us; 8us; 9us; 9us; 9us; 10us; 10us; 10us; 10us; 10us; 10us; 10us; 10us; 10us; 11us; 11us; 11us; 11us; 11us; 12us; 12us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 65535us; 65535us; 65535us; 16387us; 16388us; 16389us; 65535us; 65535us; 65535us; 65535us; 16391us; 65535us; 65535us; 65535us; 16392us; 65535us; 65535us; 65535us; 16393us; 16394us; 16395us; 65535us; 16396us; 16398us; 65535us; 16399us; 16401us; 16402us; 16403us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16407us; 65535us; 16408us; 65535us; 16409us; 16410us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16415us; 16416us; |]
let _fsyacc_reductions ()  =    [| 
# 257 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : ParseResult option)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 266 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'prog)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "PrologParser.fsy"
                                   _1 
                   )
# 46 "PrologParser.fsy"
                 : ParseResult option));
# 277 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "PrologParser.fsy"
                              None 
                   )
# 49 "PrologParser.fsy"
                 : 'prog));
# 287 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'goal)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "PrologParser.fsy"
                                                       Some <| CallParseResult _3 
                   )
# 50 "PrologParser.fsy"
                 : 'prog));
# 298 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'fact)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "PrologParser.fsy"
                               Some <| RuleParseResult _1 
                   )
# 51 "PrologParser.fsy"
                 : 'prog));
# 309 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'rule)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "PrologParser.fsy"
                               Some <| RuleParseResult _1 
                   )
# 52 "PrologParser.fsy"
                 : 'prog));
# 320 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'signature)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "PrologParser.fsy"
                                    Rule(_1, True) 
                   )
# 55 "PrologParser.fsy"
                 : 'fact));
# 331 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'signature)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "PrologParser.fsy"
                                                            Rule(_1, _4) 
                   )
# 58 "PrologParser.fsy"
                 : 'rule));
# 343 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameterList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "PrologParser.fsy"
                                                                        Signature(_1, _3) 
                   )
# 61 "PrologParser.fsy"
                 : 'signature));
# 355 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'termList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "PrologParser.fsy"
                                                                   Solve.Rule.Goal(Solve.TermTypes.Structure(_1, _3)) 
                   )
# 64 "PrologParser.fsy"
                 : 'goal));
# 367 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "PrologParser.fsy"
                                  Parameter(_1) 
                   )
# 67 "PrologParser.fsy"
                 : 'parameter));
# 378 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameter)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 70 "PrologParser.fsy"
                                    [_1] 
                   )
# 70 "PrologParser.fsy"
                 : 'parameterList));
# 389 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameterList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'parameter)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 71 "PrologParser.fsy"
                                                           _1@[_3] 
                   )
# 71 "PrologParser.fsy"
                 : 'parameterList));
# 401 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 72 "PrologParser.fsy"
                          [] 
                   )
# 72 "PrologParser.fsy"
                 : 'parameterList));
# 411 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 75 "PrologParser.fsy"
                               [_1] 
                   )
# 75 "PrologParser.fsy"
                 : 'termList));
# 422 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'termList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 76 "PrologParser.fsy"
                                                 _1@[_3] 
                   )
# 76 "PrologParser.fsy"
                 : 'termList));
# 434 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 77 "PrologParser.fsy"
                          [] 
                   )
# 77 "PrologParser.fsy"
                 : 'termList));
# 444 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 80 "PrologParser.fsy"
                                  True 
                   )
# 80 "PrologParser.fsy"
                 : 'body));
# 454 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 81 "PrologParser.fsy"
                                False 
                   )
# 81 "PrologParser.fsy"
                 : 'body));
# 464 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'goal)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 82 "PrologParser.fsy"
                               CallExpression(_1) 
                   )
# 82 "PrologParser.fsy"
                 : 'body));
# 475 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 83 "PrologParser.fsy"
                                           CalcExpr(_1, _3) 
                   )
# 83 "PrologParser.fsy"
                 : 'body));
# 487 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 84 "PrologParser.fsy"
                                          AndExpression(_1, _3) 
                   )
# 84 "PrologParser.fsy"
                 : 'body));
# 499 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'body)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "PrologParser.fsy"
                                          OrExpression(_1, _3) 
                   )
# 85 "PrologParser.fsy"
                 : 'body));
# 511 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 86 "PrologParser.fsy"
                                                EqExpr(_1, _3) 
                   )
# 86 "PrologParser.fsy"
                 : 'body));
# 523 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 87 "PrologParser.fsy"
                                                      GrExpr(_1, _3) 
                   )
# 87 "PrologParser.fsy"
                 : 'body));
# 535 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 88 "PrologParser.fsy"
                                                   LeExpr(_1, _3) 
                   )
# 88 "PrologParser.fsy"
                 : 'body));
# 547 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 91 "PrologParser.fsy"
                               Value(CalcAny(_1)) 
                   )
# 91 "PrologParser.fsy"
                 : 'calcExpr));
# 558 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 92 "PrologParser.fsy"
                                                 Plus(CalcInner(_1), CalcInner(_3)) 
                   )
# 92 "PrologParser.fsy"
                 : 'calcExpr));
# 570 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 93 "PrologParser.fsy"
                                                  Subsctruct(CalcInner(_1), CalcInner(_3)) 
                   )
# 93 "PrologParser.fsy"
                 : 'calcExpr));
# 582 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 94 "PrologParser.fsy"
                                                     Multiply(CalcInner(_1), CalcInner(_3)) 
                   )
# 94 "PrologParser.fsy"
                 : 'calcExpr));
# 594 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'calcExpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 95 "PrologParser.fsy"
                                                  Division(CalcInner(_1), CalcInner(_3)) 
                   )
# 95 "PrologParser.fsy"
                 : 'calcExpr));
# 606 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 98 "PrologParser.fsy"
                              TypedTerm(TypedNumberTerm(NumberTerm (float _1))) 
                   )
# 98 "PrologParser.fsy"
                 : 'term));
# 617 "PrologParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 99 "PrologParser.fsy"
                              VariableTerm(Variable(_1)) 
                   )
# 99 "PrologParser.fsy"
                 : 'term));
|]
# 629 "PrologParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 27;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : ParseResult option =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
