image:
  - Visual Studio 2019
  - Ubuntu
init:
  - git config --global core.autocrlf input
install:
  - dotnet tool restore
version: 0.0.1.{build}
build_script:
  - sh: ./build.sh
  - cmd: build.cmd
after_build:
  - sh: bash <(curl -s https://codecov.io/bash)
  - cmd: bash <(curl -s https://codecov.io/bash)
on_failure:
  - appveyor PushArtifact FAKE.svclog
test: off
artifacts:
  - path: bin
    name: bin
  - path: 'nuget\dotnetcore\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\legacy\*.nupkg'
    type: NuGetPackage
  - path: 'nuget\dotnetcore\Fake.netcore\*.zip'
    type: Zip