// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Solve.Terminal")]
[assembly: AssemblyProduct("Solve")]
[assembly: AssemblyDescription("Prolog F# implementation")]
[assembly: AssemblyVersion("0.0.2")]
[assembly: AssemblyFileVersion("0.0.2")]
[assembly: AssemblyConfiguration("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Solve.Terminal";
        internal const System.String AssemblyProduct = "Solve";
        internal const System.String AssemblyDescription = "Prolog F# implementation";
        internal const System.String AssemblyVersion = "0.0.2";
        internal const System.String AssemblyFileVersion = "0.0.2";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
