// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Solve.Terminal")>]
[<assembly: AssemblyProductAttribute("Solve")>]
[<assembly: AssemblyDescriptionAttribute("Prolog F# implementation")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Solve.Terminal"
    let [<Literal>] AssemblyProduct = "Solve"
    let [<Literal>] AssemblyDescription = "Prolog F# implementation"
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
    let [<Literal>] AssemblyConfiguration = "Release"
